### PR TITLE
Update NoDeleteMessages.plugin.js

### PR DESCRIPTION
**Pull request by ShiiroSan**

### CODE REVIEW

**Comment by Hiroshi18** [comment]
This PR fixed the problem with the missing red color of the deleted message and images but when I tested it the edited messages are no longer working. 

The original message becomes gray but it doesnt show the new message.

Before editing
image

After
image

But the delete is working again
image

And with images is also working

Before 
image

After deleting
image

**Comment by Hiroshi18** [comment]
This could have been caused by a new update on discord

**Comment by Sintinium** [comment]
Edited messages also doesn't show messages for me after the recent update

**Comment by ShiiroSan** [comment]
Updated it to work with recent issue. 

> Removed parserFor function. It was useless and it's causing the current issue.

**Comment by Hiroshi18** [comment]
Great job! 

It seems to be working now :)

**Review by Hiroshi18 — APPROVED** [review]

**Comment by KaKi87** [comment]
Hello, any news on this ? Thanks

**Comment by Hiroshi18** [comment]
it should be working now

**Comment by KaKi87** [comment]
It's just like you said earlier : edited messages not displayed.

**Comment by Hiroshi18** [comment]
You could manually use it manually for now till the maintainer accept the PR

Go to your plugin folder and copy and paste the code in https://github.com/ShiiroSan/BetterDiscordTrustedUnofficialPlugins/blob/master/NoDeleteMessages/NoDeleteMessages.plugin.js to you local plugin file NoDeleteMessages.plugin.js t

**Comment by KaKi87** [comment]
> till the maintainer accept the PR

But...

2019-10-26 19_10_56-Update NoDeleteMessages plugin js by ShiiroSan · Pull Request #18 · Mega-Mewthre

**Comment by KaKi87** [comment]
Well, I'm still having the same issue even after reinstalling the plugin using the link you gave me.

**Pull request merged**
