### PR TITLE
Update NoDeleteMessages.plugin.js

### PR DESCRIPTION
**Pull request by ShiiroSan**
Patched a new discord update.

### CODE REVIEW

**Comment by ShiiroSan** [comment]
Reported by EmptySoul.

**Comment by TheOPtimal** [comment]
Please merge this, this version works and t he original doesn't.

**Comment by ShiiroSan** [comment]
Newest update fix #32 and #33 (dupe of 32).

**Comment by Hiroshi18** [comment]
Unfortunately this doesn't work anymore after the update for BetterDiscord 1.2.4.

**Comment by ShiiroSan** [comment]
I stopped supporting it. There's many good alternatives available.

**Comment by rakion99** [comment]
in case someone want an alternative this is the one im using and works fine: https://1lighty.github.io/BetterDiscordStuff/?plugin=MessageLoggerV2

**Comment by Hiroshi18** [comment]
@rakion99  Thank you I will try it out

**Comment by Hiroshi18** [comment]
@ShiiroSan thank you for supporting it this far it was my favorite plugin in discord.

**Pull request closed without merging**
