### PR TITLE
Nocrypticlines

### PR DESCRIPTION
**Pull request by ShiiroSan**
Right now this is just a proposition.
These lines are not need anymore. 
This might allow to patch it easier. Removing these lines also patch the emoji issue submitted by _Worried_ and _Zotrix_.
Add to this the fact that people complain about it #13.

This proposition include #21.

### CODE REVIEW

**Comment by Evernow** [comment]
Should probably merge these into master

**Comment by ShiiroSan** [comment]
> Should probably merge these into master

image

**Comment by nathan78906** [comment]
@Mega-Mewthree please merge this

**Comment by ShiiroSan** [comment]
No more needed.

**Pull request closed without merging**
